### ISSUE TITLE
"Cannot open load file: No such file or directory, helm-occur"

### ISSUE THREAD

**Issue by Gahamelas** [emacsorphanage/helm-ag#353] opened 2020-05-21 05:30 UTC
Im on OS >10- Emacs version: 26.3.
Last helm-ag version.

I just installed the package and when I M-x helm-ag I get:

`Cannot open load file: No such file or directory, helm-occur`

Thanks,
GM

**Comment by syohex** [comment] 2020-05-21 06:00
I cannot reproduce this issue. Did you install `helm` package ? If you use so old helm packages, Please upgrade it and retry.

**Comment by Gahamelas** [comment] 2020-05-21 07:07
1. I uninstalled helm-ag
2. I uninstalled helm and helm-core, which were quite old, and reinstalled. 
3. I reinstalled helm-ag
4. I restarted Emacs

`M-x helm-ag `gives me now this error:

`Searching for  program: no such file or directory, ag`

Questions:
1. Shall I add anything to my init file?
2. In the instructions it says:

```
Requirements
Emacs 24 or higher
helm 1.7.7 or higher
The Silver Searcher 0.29.0 or higher.
```

Is The Silver Searcher something I must install separately?
Thanks!
GM

**Comment by syohex** [comment] 2020-05-21 07:59
> 1. Shall I add anything to my init file?

No if you install `helm-ag` by package manager.

> Is The Silver Searcher something I must install separately?

https://github.com/ggreer/the_silver_searcher

Yes, please install it. `helm-ag` also supports ripgrep if you want to use ripgrep please read documentation(https://github.com/emacsorphanage/helm-ag#ripgrep)

**Comment by Gahamelas** [comment] 2020-05-21 08:06
Thanks, that was pretty silly of me, not having the package AG installed (in all honesty, I did not know the package myself, so couldn't connect the dots that AG refered to The Silver Searcher. Thanks for the understanding! Now it works :)

Yes, I also use helm-rg, and I have wondered what is the difference between them in terms of features. But I suppose this is not the place to ask.

**Comment by jcs090218** [comment] 2020-11-25 07:17
Glad the issue has been resolved! Close this issue now. 😄 

Thanks for reporting this issue to use!

**Closed by jcs090218** 2020-11-25 07:17 UTC
